modbusd: /home/travis/build/taka-wang/modbusd/mbtcp.c File Reference
/home/travis/build/taka-wang/modbusd/mbtcp.c File Reference
modbus tcp
#include "mb.h"
Functions
bool mbtcp_init_handle (mbtcp_handle_s **ptr_handle, char *ip, char *port)
Init mbtcp handle (to hashtable) and try to connect.
bool mbtcp_get_handle (mbtcp_handle_s **ptr_handle, char *ip, char *port)
Get mbtcp handle from hashtable.
void mbtcp_list_handles ()
List all handles in mbtcp hash table.
bool mbtcp_do_connect (mbtcp_handle_s *handle, char **reason)
Connect to mbtcp slave via mbtcp hashed handle.
bool mbtcp_get_connection_status (mbtcp_handle_s *handle)
Get mbtcp handle's connection status.
char * mbtcp_cmd_hanlder (cJSON *req, mbtcp_fc fc)
Generic mbtcp command handler.
char * mbtcp_set_response_timeout (int tid, long int timeout)
Set mbtcp response timeout in usec.
char * mbtcp_fc1_req (mbtcp_handle_s *handle, cJSON *req)
Modbus TCP Read coils.
char * mbtcp_fc2_req (mbtcp_handle_s *handle, cJSON *req)
Modbus TCP Read discrete input.
char * mbtcp_fc3_req (mbtcp_handle_s *handle, cJSON *req)
Modbus TCP Read holding registers.
char * mbtcp_fc4_req (mbtcp_handle_s *handle, cJSON *req)
Modbus TCP Read input registers.
char * mbtcp_fc5_req (mbtcp_handle_s *handle, cJSON *req)
Modbus TCP Write single coil.
char * mbtcp_fc6_req (mbtcp_handle_s *handle, cJSON *req)
Modbus TCP Write single register.
char * mbtcp_fc15_req (mbtcp_handle_s *handle, cJSON *req)
Modbus TCP Write multiple coils.
char * mbtcp_fc16_req (mbtcp_handle_s *handle, cJSON *req)
Modbus TCP Write multiple registers.
Variables
int enable_syslog
uint32_t tcp_conn_timeout_usec = 200000
Detailed Description
modbus tcp
Author
taka-wang
Function Documentation
char* mbtcp_cmd_hanlder (cJSON * req, mbtcp_fc fc)
Generic mbtcp command handler.
Parameters
req cJSON request object.
fc Function pointer to modbus tcp FC handler.
Returns
Modbus response string in JSON format.
References BEGIN, mbtcp_handle_s::ctx, enable_syslog, json_get_int(), LOG, and set_modbus_fail_resp_str().
Referenced by main().
 {
     BEGIN(enable_syslog);
     mbtcp_handle_s *handle = NULL;
     int tid  = json_get_int(req, "tid");
     if (lazy_init_mbtcp_handle(&handle, req))
     {
         char * reason = NULL;
         if (lazy_mbtcp_connect(handle, &reason))
         {
             // set slave id
             int slave = json_get_int(req, "slave");
             LOG(enable_syslog, "slave id: %d", slave);
             modbus_set_slave(handle->ctx, slave);
             return fc(handle, req);
         }
         else
         {
             // [enhance]: get reason from modbus response
             return set_modbus_fail_resp_str(tid, reason);
         }
     }
     else
     {
         return set_modbus_fail_resp_str(tid, "init modbus tcp handle fail");
     }
 }
bool mbtcp_do_connect (mbtcp_handle_s * handle, char ** reason)
Connect to mbtcp slave via mbtcp hashed handle.
Parameters
handle Mbtcp handle.
reason Fail reason string.
Returns
Success or not.
References BEGIN, mbtcp_handle_s::connected, mbtcp_handle_s::ctx, enable_syslog, ERR, mbtcp_key_s::ip, mbtcp_handle_s::key, LOG, and mbtcp_key_s::port.
Referenced by mbtcp_init_handle(), and test_init_tcp_handle_and_connect().
 {
     BEGIN(enable_syslog);
     if (handle == NULL)
     {
         ERR(enable_syslog, "NULL handle");
         *reason = "NULL handle";
         return false;
     }
     if (modbus_connect(handle->ctx) == -1)
     {
         ERR(enable_syslog, "Connection failed: %s", modbus_strerror(errno));
         *reason = (char *)modbus_strerror(errno);
         return false;
     }
     else
     {
         LOG(enable_syslog, "%s:%s connected", handle->key.ip, handle->key.port);
         handle->connected = true;
         return true;
     }
 }
char* mbtcp_fc15_req (mbtcp_handle_s * handle, cJSON * req)
Modbus TCP Write multiple coils.
Parameters
handle Mbtcp handle.
req cJSON request object.
Returns
Modbus response string in JSON format.
References BEGIN, and enable_syslog.
Referenced by main().
 {
     BEGIN(enable_syslog);
     return mbtcp_multi_write_req(15, handle, req);
 }
char* mbtcp_fc16_req (mbtcp_handle_s * handle, cJSON * req)
Modbus TCP Write multiple registers.
Parameters
handle Mbtcp handle.
req cJSON request object.
Returns
Modbus response string in JSON format.
References BEGIN, and enable_syslog.
Referenced by main().
 {
     BEGIN(enable_syslog);
     return mbtcp_multi_write_req(16, handle, req);
 }
char* mbtcp_fc1_req (mbtcp_handle_s * handle, cJSON * req)
Modbus TCP Read coils.
Parameters
handle Mbtcp handle.
req cJSON request object.
Returns
Modbus response string in JSON format.
References BEGIN, and enable_syslog.
Referenced by main().
 {
     BEGIN(enable_syslog);
     return mbtcp_read_bit_req(1, handle, req);
 }
char* mbtcp_fc2_req (mbtcp_handle_s * handle, cJSON * req)
Modbus TCP Read discrete input.
Parameters
handle Mbtcp handle.
req cJSON request object.
Returns
Modbus response string in JSON format.
References BEGIN, and enable_syslog.
Referenced by main().
 {
     BEGIN(enable_syslog);
     return mbtcp_read_bit_req(2, handle, req);
 }
char* mbtcp_fc3_req (mbtcp_handle_s * handle, cJSON * req)
Modbus TCP Read holding registers.
Parameters
handle Mbtcp handle.
req cJSON request object.
Returns
Modbus response string in JSON format.
References BEGIN, and enable_syslog.
Referenced by main().
 {
     BEGIN(enable_syslog);
     return mbtcp_read_reg_req(3, handle, req);
 }
char* mbtcp_fc4_req (mbtcp_handle_s * handle, cJSON * req)
Modbus TCP Read input registers.
Parameters
handle Mbtcp handle.
req cJSON request object.
Returns
Modbus response string in JSON format.
References BEGIN, and enable_syslog.
Referenced by main().
 {
     BEGIN(enable_syslog);
     return mbtcp_read_reg_req(4, handle, req);
 }
char* mbtcp_fc5_req (mbtcp_handle_s * handle, cJSON * req)
Modbus TCP Write single coil.
Parameters
handle Mbtcp handle.
req cJSON request object.
Returns
Modbus response string in JSON format.
References BEGIN, and enable_syslog.
Referenced by main().
 {
     BEGIN(enable_syslog);
     return mbtcp_single_write_req(5, handle, req);
 }
char* mbtcp_fc6_req (mbtcp_handle_s * handle, cJSON * req)
Modbus TCP Write single register.
Parameters
handle Mbtcp handle.
req cJSON request object.
Returns
Modbus response string in JSON format.
References BEGIN, and enable_syslog.
Referenced by main().
 {
     BEGIN(enable_syslog);
     return mbtcp_single_write_req(6, handle, req);
 }
bool mbtcp_get_connection_status (mbtcp_handle_s * handle)
Get mbtcp handle's connection status.
Parameters
handle Mbtcp handle.
Returns
Success or not.
References BEGIN, mbtcp_handle_s::connected, enable_syslog, ERR, mbtcp_key_s::ip, mbtcp_handle_s::key, LOG, and mbtcp_key_s::port.
Referenced by test_init_tcp_handle_and_connect().
 {
     BEGIN(enable_syslog);
     if (handle == NULL)
     {
         ERR(enable_syslog, "NULL handle");
         return false;
     }
     LOG(enable_syslog, "%s:%s connected: %s", handle->key.ip,
                                               handle->key.port,
                                               handle->connected ? "true" : "false");
     return handle->connected;
 }
bool mbtcp_get_handle (mbtcp_handle_s ** ptr_handle, char * ip, char * port)
Get mbtcp handle from hashtable.
Parameters
ptr_handle Pointer to mbtcp handle.
ip IP address string.
port Modbus TCP server port string or service name.
Returns
Success or not.
References BEGIN, enable_syslog, ERR, HASH_FIND, mbtcp_key_s::ip, mbtcp_handle_s::key, LOG, and mbtcp_key_s::port.
Referenced by test_init_tcp_handle_and_connect().
 {
     BEGIN(enable_syslog);
     mbtcp_handle_s query, *hash_ctx;
     memset(&query, 0, sizeof(mbtcp_handle_s));
     strcpy(query.key.ip, ip);
     strcpy(query.key.port, port);
     HASH_FIND(hh, mbtcp_htable, &query.key, sizeof(mbtcp_key_s), hash_ctx);
     if (hash_ctx != NULL)
     {
         LOG(enable_syslog, "tcp server %s:%s found", hash_ctx->key.ip, hash_ctx->key.port);
         // call by reference to `mbtcp handle address`
         *ptr_handle = hash_ctx;
         return true;
     }
     else
     {
         ERR(enable_syslog, "tcp server %s:%s not found", query.key.ip, query.key.port);
         *ptr_handle = NULL;
         return false; // not found
     }
 }
bool mbtcp_init_handle (mbtcp_handle_s ** ptr_handle, char * ip, char * port)
Init mbtcp handle (to hashtable) and try to connect.
Parameters
ptr_handle Pointer to mbtcp handle.
ip IP address string.
port Modbus TCP server port string.
Returns
Success or not.
References BEGIN, mbtcp_handle_s::connected, mbtcp_handle_s::ctx, enable_syslog, ERR, HASH_ADD, mbtcp_key_s::ip, mbtcp_handle_s::key, LOG, mbtcp_do_connect(), mbtcp_key_s::port, and tcp_conn_timeout_usec.
Referenced by test_init_tcp_handle_and_connect().
 {
     BEGIN(enable_syslog);
     // create a mbtcp context
     modbus_t *ctx = modbus_new_tcp_pi(ip, port);
     if (ctx == NULL)
     {
         ERR(enable_syslog, "Unable to allocate mbtcp context");
         return false; // fail to allocate context
     }
     // set tcp connection timeout
     modbus_set_response_timeout(ctx, 0, tcp_conn_timeout_usec);
     LOG(enable_syslog, "set response timeout:%d", tcp_conn_timeout_usec);
     // @add context to mbtcp hashtable
     mbtcp_handle_s *handle;
     handle = (mbtcp_handle_s*)malloc(sizeof(mbtcp_handle_s));
     // let alignment bytes being set to zero-value!!
     memset(handle, 0, sizeof(mbtcp_handle_s));
     handle->connected = false;
     strcpy(handle->key.ip, ip);
     strcpy(handle->key.port, port);
     handle->ctx = ctx;
     HASH_ADD(hh, mbtcp_htable, key, sizeof(mbtcp_key_s), handle);
     LOG(enable_syslog, "Add %s:%s to mbtcp hashtable", handle->key.ip, mbtcp_htable->key.port);
     // call by reference to `mbtcp handle address`
     *ptr_handle = handle;
     // @connect to server
     char * reason = NULL;
     mbtcp_do_connect(handle, &reason);
     return true;
 }
void mbtcp_list_handles ()
List all handles in mbtcp hash table.
Returns
Void.
References BEGIN, enable_syslog, mbtcp_handle_s::hh, mbtcp_key_s::ip, mbtcp_handle_s::key, UT_hash_handle::next, and mbtcp_key_s::port.
 {
     BEGIN(enable_syslog);
     mbtcp_handle_s * handle;
     for (handle = mbtcp_htable; handle != NULL; handle = handle->hh.next)
     {
         printf("ip:%s, port:%s\n", handle->key.ip, handle->key.port);
     }
 }
char* mbtcp_set_response_timeout (int tid, long int timeout)
Set mbtcp response timeout in usec.
Parameters
tid Transaction ID.
timeout Timeout in usec.
Returns
Modbus response string in JSON format.
References BEGIN, cJSON_AddNumberToObject, cJSON_AddStringToObject, cJSON_CreateObject(), cJSON_Delete(), cJSON_PrintUnformatted(), enable_syslog, LOG, and tcp_conn_timeout_usec.
Referenced by main().
 {
     BEGIN(enable_syslog);
     // set timeout
     tcp_conn_timeout_usec = timeout;
     cJSON *resp_root;
     resp_root = cJSON_CreateObject();
     cJSON_AddNumberToObject(resp_root, "tid", tid);
     cJSON_AddStringToObject(resp_root, "status", "ok");
     char * resp_json_string = cJSON_PrintUnformatted(resp_root);
     LOG(enable_syslog, "resp: %s", resp_json_string);
     // clean up
     cJSON_Delete(resp_root);
     return resp_json_string;
 }
Variable Documentation
int enable_syslog
Referenced by main(), mbtcp_cmd_hanlder(), mbtcp_do_connect(), mbtcp_fc15_req(), mbtcp_fc16_req(), mbtcp_fc1_req(), mbtcp_fc2_req(), mbtcp_fc3_req(), mbtcp_fc4_req(), mbtcp_fc5_req(), mbtcp_fc6_req(), mbtcp_get_connection_status(), mbtcp_get_handle(), mbtcp_init_handle(), mbtcp_list_handles(), mbtcp_set_response_timeout(), test_init_tcp_handle_and_connect(), test_multiple_add_find(), test_multiple_add_find_zhahs(), and test_single_add_find().
uint32_t tcp_conn_timeout_usec = 200000
Referenced by mbtcp_init_handle(), and mbtcp_set_response_timeout().